/**
 * Returns the JavaScript code for the webview.
 */
export function getWebviewScript(): string {
  return [
    // ── Markdown renderer ──
    `function renderMd(src) {`,
    `  if (!src) return "";`,
    `  var h = "";`,
    `  var lines = src.split("\\n");`,
    `  var inCode = false, codeLang = "", codeLines = [];`,
    `  var inUl = false, inOl = false;`,
    `  for (var i = 0; i < lines.length; i++) {`,
    `    var line = lines[i];`,
    `    if (line.startsWith("\`\`\`")) {`,
    `      if (!inCode) {`,
    `        if (inUl) { h += "</ul>"; inUl = false; }`,
    `        if (inOl) { h += "</ol>"; inOl = false; }`,
    `        inCode = true; codeLang = line.slice(3).trim(); codeLines = [];`,
    `      } else {`,
    `        var cid = "c" + Math.random().toString(36).slice(2,8);`,
    `        h += '<pre><div class="code-head"><span>' + esc(codeLang||"text") + '</span><button class="copy-btn" data-codeid="' + cid + '">Copy</button></div><code id="' + cid + '">' + esc(codeLines.join("\\n")) + '</code></pre>';`,
    `        inCode = false; codeLang = ""; codeLines = [];`,
    `      }`,
    `      continue;`,
    `    }`,
    `    if (inCode) { codeLines.push(line); continue; }`,
    `    var isUlItem = /^[\\-\\*] /.test(line);`,
    `    var isOlItem = /^\\d+\\. /.test(line);`,
    `    if (inUl && !isUlItem) { h += "</ul>"; inUl = false; }`,
    `    if (inOl && !isOlItem) { h += "</ol>"; inOl = false; }`,
    `    if (line.indexOf("|") > -1 && i+1 < lines.length && /^[\\|\\s:\\-]+$/.test(lines[i+1])) {`,
    `      var headers = line.split("|").map(function(c){return c.trim();}).filter(Boolean);`,
    `      i++;`,
    `      h += '<table><thead><tr>';`,
    `      headers.forEach(function(hd){ h += '<th>' + inlineMd(esc(hd)) + '</th>'; });`,
    `      h += '</tr></thead><tbody>';`,
    `      while (i+1 < lines.length && lines[i+1].indexOf("|") > -1) {`,
    `        i++;`,
    `        var cells = lines[i].split("|").map(function(c){return c.trim();}).filter(Boolean);`,
    `        h += '<tr>';`,
    `        cells.forEach(function(cl){ h += '<td>' + inlineMd(esc(cl)) + '</td>'; });`,
    `        h += '</tr>';`,
    `      }`,
    `      h += '</tbody></table>'; continue;`,
    `    }`,
    `    if (line.startsWith("#### ")) { h += "<h4>" + inlineMd(esc(line.slice(5))) + "</h4>"; continue; }`,
    `    if (line.startsWith("### "))  { h += "<h3>" + inlineMd(esc(line.slice(4))) + "</h3>"; continue; }`,
    `    if (line.startsWith("## "))   { h += "<h2>" + inlineMd(esc(line.slice(3))) + "</h2>"; continue; }`,
    `    if (line.startsWith("# "))    { h += "<h1>" + inlineMd(esc(line.slice(2))) + "</h1>"; continue; }`,
    `    if (/^---+$/.test(line)) { h += "<hr/>"; continue; }`,
    `    if (line.startsWith("> ")) { h += "<blockquote>" + inlineMd(esc(line.slice(2))) + "</blockquote>"; continue; }`,
    `    if (isUlItem) {`,
    `      if (!inUl) { h += "<ul>"; inUl = true; }`,
    `      h += "<li>" + inlineMd(esc(line.replace(/^[\\-\\*] /,""))) + "</li>"; continue;`,
    `    }`,
    `    if (isOlItem) {`,
    `      if (!inOl) { h += "<ol>"; inOl = true; }`,
    `      h += "<li>" + inlineMd(esc(line.replace(/^\\d+\\. /,""))) + "</li>"; continue;`,
    `    }`,
    `    if (line.trim() === "") { h += "<br/>"; continue; }`,
    `    h += "<p>" + inlineMd(esc(line)) + "</p>";`,
    `  }`,
    `  if (inUl) h += "</ul>";`,
    `  if (inOl) h += "</ol>";`,
    `  if (inCode && codeLines.length > 0) {`,
    `    var cid2 = "c" + Math.random().toString(36).slice(2,8);`,
    `    h += '<pre><div class="code-head"><span>' + esc(codeLang||"text") + '</span></div><code id="' + cid2 + '">' + esc(codeLines.join("\\n")) + '</code></pre>';`,
    `  }`,
    `  return h;`,
    `}`,
    `function inlineMd(s) {`,
    `  s = s.replace(/\`([^\`]+)\`/g, '<code>$1</code>');`,
    `  s = s.replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>');`,
    `  s = s.replace(/__(.+?)__/g, '<strong>$1</strong>');`,
    `  s = s.replace(/\\*(.+?)\\*/g, '<em>$1</em>');`,
    `  s = s.replace(/_(.+?)_/g, '<em>$1</em>');`,
    `  s = s.replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '<a href="$2" target="_blank">$1</a>');`,
    `  return s;`,
    `}`,
    `function esc(t) { return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }`,

    // ── DOM refs ──
    `var vscodeApi = acquireVsCodeApi();`,
    `var chatEl = document.getElementById("chat");`,
    `var inputEl = document.getElementById("input");`,
    `var sendBtnEl = document.getElementById("sendBtn");`,
    `var generating = false, currentStreamEl = null, streamText = "";`,

    // ── Input auto-resize ──
    `inputEl.addEventListener("input", function() {`,
    `  inputEl.style.height = "24px";`,
    `  inputEl.style.height = Math.min(inputEl.scrollHeight, 120) + "px";`,
    `});`,
    `inputEl.addEventListener("keydown", function(e) {`,
    `  if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); doSend(); }`,
    `});`,
    `sendBtnEl.addEventListener("click", function() {`,
    `  if (generating) { vscodeApi.postMessage({type:"stopGeneration"}); }`,
    `  else { doSend(); }`,
    `});`,

    // ── Toolbar buttons ──
    `document.getElementById("pickFileBtn").addEventListener("click", function() { vscodeApi.postMessage({type:"pickFile"}); });`,
    `document.getElementById("newChatBtn").addEventListener("click", function() { vscodeApi.postMessage({type:"newChat"}); });`,
    `document.getElementById("threadsBtn").addEventListener("click", function() {`,
    `  vscodeApi.postMessage({type:"listThreads"});`,
    `  document.getElementById("threadPanel").classList.add("open");`,
    `});`,
    `document.getElementById("closeThreads").addEventListener("click", function() {`,
    `  document.getElementById("threadPanel").classList.remove("open");`,
    `});`,

    // ── Tool icon map ──
    `var TOOL_ICONS = {`,
    `  bash:"\uD83D\uDCBB", fileread:"\uD83D\uDCC4", filewrite:"\u270F\uFE0F", fileedit:"\u270F\uFE0F",`,
    `  glob:"\uD83D\uDD0D", grep:"\uD83D\uDD0D", listdirectory:"\uD83D\uDCC1", ls:"\uD83D\uDCC1",`,
    `  webfetch:"\uD83C\uDF10", todowrite:"\uD83D\uDCCB",`,
    `  read_file:"\uD83D\uDCC4", write_file:"\u270F\uFE0F", edit_file:"\u270F\uFE0F",`,
    `};`,
    `function toolIcon(name) {`,
    `  var key = name.toLowerCase().replace("tool","");`,
    `  return TOOL_ICONS[key] || TOOL_ICONS[name] || "\uD83D\uDD27";`,
    `}`,

    // ── Delegated click handler ──
    `document.addEventListener("click", function(e) {`,
    `  var el = e.target;`,
    `  if (el.dataset && el.dataset.prompt) { inputEl.value = el.dataset.prompt; doSend(); }`,
    `  if (el.classList.contains("copy-btn") && el.dataset.codeid) {`,
    `    var codeEl = document.getElementById(el.dataset.codeid);`,
    `    if (codeEl) { navigator.clipboard.writeText(codeEl.textContent||""); el.textContent="Copied!"; setTimeout(function(){el.textContent="Copy";},1800); }`,
    `  }`,
    `  var toolHead = el.classList.contains("tool-head") ? el : (el.closest ? el.closest(".tool-head") : null);`,
    `  if (toolHead) { toolHead.closest(".tool").classList.toggle("open"); }`,
    `  var thinkHead = el.classList.contains("thinking-head") ? el : (el.closest ? el.closest(".thinking-head") : null);`,
    `  if (thinkHead) { thinkHead.closest(".thinking-block").classList.toggle("open"); }`,
    `  if (el.dataset && el.dataset.delthread) {`,
    `    e.stopPropagation();`,
    `    vscodeApi.postMessage({type:"deleteThread", id: el.dataset.delthread});`,
    `  }`,
    `});`,

    // ── Send ──
    `function doSend() {`,
    `  var t = inputEl.value.trim();`,
    `  if (!t || generating) return;`,
    `  vscodeApi.postMessage({ type: "sendMessage", text: t });`,
    `  inputEl.value = ""; inputEl.style.height = "24px";`,
    `}`,

    // ── Add message bubble ──
    `function addMsg(role, content) {`,
    `  var w = chatEl.querySelector(".welcome"); if(w) w.remove();`,
    `  var d = document.createElement("div"); d.className = "msg " + role;`,
    `  var avatarLetter = role === "user" ? "U" : "M";`,
    `  var displayName  = role === "user" ? "You" : "Milo Code";`,
    `  var body = role === "assistant" ? renderMd(content) : "<p>" + esc(content) + "</p>";`,
    `  d.innerHTML = '<div class="msg-head"><div class="avatar">' + avatarLetter + '</div><span class="msg-name">' + displayName + '</span></div><div class="msg-body">' + body + '</div>';`,
    `  chatEl.appendChild(d); chatEl.scrollTop = chatEl.scrollHeight; return d;`,
    `}`,

    // ── Processing indicator helper ──
    `function showProcessing() {`,
    `  removeProcessing();`,
    `  var ti = document.createElement("div");`,
    `  ti.id = "thinking-indicator"; ti.className = "msg assistant";`,
    `  ti.innerHTML = '<div class="msg-head"><div class="avatar">M</div><span class="msg-name">Milo Code</span></div>'`,
    `    + '<div class="msg-body thinking-wrap">'`,
    `    + '<span class="thinking-dots"><span></span><span></span><span></span></span>'`,
    `    + '<span class="thinking-label">Processing...</span>'`,
    `    + '</div>';`,
    `  chatEl.appendChild(ti); chatEl.scrollTop = chatEl.scrollHeight;`,
    `}`,
    `function removeProcessing() {`,
    `  var ti = document.getElementById("thinking-indicator"); if(ti) ti.remove();`,
    `}`,

    // ── Message handler ──
    `window.addEventListener("message", function(e) {`,
    `  var m = e.data;`,
    `  switch(m.type) {`,

    `    case "addMessage": addMsg(m.role, m.content); break;`,

    `    case "generationStarted":`,
    `      generating = true;`,
    `      sendBtnEl.innerHTML = "&#9632; Stop";`,
    `      sendBtnEl.className = "stop";`,
    `      var w2 = chatEl.querySelector(".welcome"); if(w2) w2.remove();`,
    `      showProcessing();`,
    `      break;`,

    `    case "streamStart":`,
    `      streamText = "";`,
    `      removeProcessing();`,
    `      currentStreamEl = addMsg("assistant", "");`,
    `      break;`,

    `    case "streamDelta":`,
    `      streamText += m.text || "";`,
    `      if (currentStreamEl) currentStreamEl.querySelector(".msg-body").innerHTML = renderMd(streamText);`,
    `      chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,

    `    case "streamEnd": currentStreamEl = null; streamText = ""; break;`,

    `    case "generationStopped":`,
    `      generating = false;`,
    `      sendBtnEl.innerHTML = "&#10148; Send";`,
    `      sendBtnEl.className = "";`,
    `      removeProcessing();`,
    `      break;`,

    `    case "toolBlock": {`,
    `      removeProcessing();`,
    `      var inputStr = "";`,
    `      try { var inp = JSON.parse(m.input||"null"); inputStr = typeof inp === "object" && inp ? Object.entries(inp).map(function(kv){return kv[0]+": "+String(kv[1]);}).join("\\n") : m.input||""; }`,
    `      catch(ex) { inputStr = m.input || ""; }`,
    `      var tb = document.createElement("div");`,
    `      tb.className = "tool"; tb.id = "tool-" + m.id;`,
    `      tb.innerHTML = '<div class="tool-head">'`,
    `        + '<span class="tool-chevron">\u25BA</span>'`,
    `        + '<span class="tool-icon">' + toolIcon(m.name) + '</span>'`,
    `        + '<span class="tool-label">' + esc(m.label || m.name) + '<span class="tool-subname"> (' + esc(m.name) + ')</span></span>'`,
    `        + '<div class="tool-spinner"></div>'`,
    `        + '</div>'`,
    `        + '<div class="tool-body">'`,
    `        + '<div class="tool-section"><div class="tool-section-head">Input</div><pre>' + esc(inputStr) + '</pre></div>'`,
    `        + '</div>';`,
    `      chatEl.appendChild(tb); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,
    `    }`,

    `    case "toolBlockUpdate": {`,
    `      var existing = document.getElementById("tool-" + m.id);`,
    `      if (existing) {`,
    `        var spinner = existing.querySelector(".tool-spinner");`,
    `        if (spinner) {`,
    `          var badge = document.createElement("span");`,
    `          if (m.status === "error") { badge.className = "tool-badge err"; badge.textContent = "\u2717 error"; }`,
    `          else { badge.className = "tool-badge ok"; badge.textContent = "\u2713 done"; }`,
    `          spinner.replaceWith(badge);`,
    `        }`,
    `        if (m.output) {`,
    `          var bd = existing.querySelector(".tool-body");`,
    `          if (bd) {`,
    `            var outSec = document.createElement("div");`,
    `            outSec.className = "tool-section " + (m.status === "error" ? "tool-output-err" : "tool-output-ok");`,
    `            outSec.innerHTML = '<div class="tool-section-head">Output</div><pre>' + esc(m.output.slice(0,800)) + (m.output.length > 800 ? "\u2026" : "") + '</pre>';`,
    `            bd.appendChild(outSec);`,
    `          }`,
    `          existing.classList.add("open");`,
    `        }`,
    `      }`,
    `      break;`,
    `    }`,

    `    case "thinkingStart": {`,
    `      removeProcessing();`,
    `      var tk = document.createElement("div");`,
    `      tk.className = "thinking-block"; tk.id = m.id;`,
    `      tk.innerHTML = '<div class="thinking-head">'`,
    `        + '<span class="thinking-chevron">\u25BA</span>'`,
    `        + '<span class="thinking-head-label">\uD83E\uDDE0 Thinking...</span>'`,
    `        + '<div class="thinking-stream-dots"><span></span><span></span><span></span></div>'`,
    `        + '</div>'`,
    `        + '<div class="thinking-body"></div>';`,
    `      chatEl.appendChild(tk); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,
    `    }`,

    `    case "thinkingDelta": {`,
    `      var tkEl = document.getElementById(m.id);`,
    `      if (tkEl) {`,
    `        var tbody = tkEl.querySelector(".thinking-body");`,
    `        if (tbody) {`,
    `          tbody.innerHTML += "<p>" + esc(m.text || "") + "</p>";`,
    `          chatEl.scrollTop = chatEl.scrollHeight;`,
    `        }`,
    `      }`,
    `      break;`,
    `    }`,

    `    case "thinkingEnd": {`,
    `      var tkEl2 = document.getElementById(m.id);`,
    `      if (tkEl2) {`,
    `        var dots = tkEl2.querySelector(".thinking-stream-dots");`,
    `        if (dots) {`,
    `          var bodyText = (tkEl2.querySelector(".thinking-body")||{textContent:""}).textContent||"";`,
    `          var cc = document.createElement("span");`,
    `          cc.className = "thinking-char-count"; cc.textContent = bodyText.trim().length + " chars";`,
    `          dots.replaceWith(cc);`,
    `        }`,
    `        var lbl = tkEl2.querySelector(".thinking-head-label");`,
    `        if (lbl) lbl.textContent = "\uD83E\uDDE0 Thought";`,
    `      }`,
    `      break;`,
    `    }`,

    `    case "todoUpdate":`,
    `      var todoEl = document.getElementById("todo-panel");`,
    `      if (!todoEl) {`,
    `        todoEl = document.createElement("div");`,
    `        todoEl.id = "todo-panel";`,
    `        todoEl.className = "todo-panel";`,
    `        var chatParent = chatEl.parentNode;`,
    `        chatParent.insertBefore(todoEl, chatEl);`,
    `      }`,
    `      todoEl.innerHTML = '<div class="todo-header">&#128203; Task progress</div>'`,
    `        + m.todos.map(function(t) {`,
    `          var icon = t.status === "done" ? "&#10003;" : t.status === "in_progress" ? "&#9654;" : t.status === "blocked" ? "&#10007;" : "&#9675;";`,
    `          var cls = "todo-item todo-" + t.status;`,
    `          return '<div class="' + cls + '">' + icon + ' <span class="todo-title">' + esc(t.title) + '</span>'`,
    `            + (t.note ? '<span class="todo-note">' + esc(t.note) + '</span>' : '') + '</div>';`,
    `        }).join("");`,
    `      break;`,

    `    case "permissionPrompt":`,
    `      removeProcessing();`,
    `      var pp = document.createElement("div"); pp.className = "permission-prompt";`,
    `      pp.innerHTML = '<div class="pp-head">&#9888;&#65039; Milo Code wants to run a shell command:</div>'`,
    `        + '<div class="pp-tool">' + esc(m.name) + '</div>'`,
    `        + '<pre class="pp-input">' + esc(m.input) + '</pre>'`,
    `        + '<div class="pp-actions">'`,
    `        + '<button class="pp-btn pp-allow" data-perm="allow">Allow once</button>'`,
    `        + '<button class="pp-btn pp-allowall" data-perm="allow_all">Allow for this chat</button>'`,
    `        + '<button class="pp-btn pp-deny" data-perm="deny">Deny</button>'`,
    `        + '</div>'`,
    `        + '<div class="pp-note">&#8505;&#65039; "Allow for this chat" only applies to this conversation and is not saved permanently.</div>';`,
    `      pp.querySelectorAll(".pp-btn").forEach(function(btn) {`,
    `        btn.addEventListener("click", function() {`,
    `          vscodeApi.postMessage({type:"permissionResponse", answer: btn.dataset.perm});`,
    `          pp.remove();`,
    `        });`,
    `      });`,
    `      chatEl.appendChild(pp); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,

    `    case "showError":`,
    `      removeProcessing();`,
    `      var errD = document.createElement("div"); errD.className = "tool";`,
    `      errD.innerHTML = '<div class="tool-head"><span class="tool-name">&#10060; Error</span><span class="tool-status err">failed</span></div>'`,
    `        + '<div class="tool-body open"><pre>' + esc(m.error) + '</pre></div>';`,
    `      chatEl.appendChild(errD); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,

    `    case "downloadProgress":`,
    `      var dlEl = document.getElementById("milo-download-progress");`,
    `      if (!dlEl) {`,
    `        dlEl = document.createElement("div"); dlEl.id = "milo-download-progress";`,
    `        dlEl.style.cssText = "padding:8px 12px;font-size:12px;color:var(--fg2);display:flex;align-items:center;gap:8px";`,
    `        dlEl.innerHTML = '<span>&#11015;&#65039;</span><span id="milo-dl-text"></span><div style="flex:1;height:3px;background:var(--bg2);border-radius:2px;overflow:hidden"><div id="milo-dl-bar" style="height:100%;background:var(--accent);transition:width 0.2s;width:0%"></div></div>';`,
    `        chatEl.appendChild(dlEl); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      }`,
    `      document.getElementById("milo-dl-text").textContent = m.text;`,
    `      document.getElementById("milo-dl-bar").style.width = m.progress + "%";`,
    `      if (m.progress >= 100) { setTimeout(function(){ var e=document.getElementById("milo-download-progress"); if(e) e.remove(); }, 2000); }`,
    `      break;`,

    `    case "clearChat":`,
    `      chatEl.innerHTML = '<div class="welcome">'`,
    `        + '<div class="welcome-logo">&#129302;</div>'`,
    `        + '<h2>Milo Code</h2>'`,
    `        + '<span class="tag">Powered by Gemma 4 &nbsp;&#183;&nbsp; Self-hosted</span>'`,
    `        + '<p>AI coding agent inside VS Code.<br>Read, write, edit files &bull; run commands &bull; persistent chat history.</p>'`,
    `        + '<div class="shortcuts">'`,
    `        + '<div class="shortcut" data-prompt="Explain this project structure to me"><span class="shortcut-icon">&#128269;</span>Explain project</div>'`,
    `        + '<div class="shortcut" data-prompt="Find and fix bugs in the code"><span class="shortcut-icon">&#128030;</span>Find &amp; fix bugs</div>'`,
    `        + '<div class="shortcut" data-prompt="Write unit tests for this project"><span class="shortcut-icon">&#9989;</span>Write tests</div>'`,
    `        + '<div class="shortcut" data-prompt="Review the code and suggest improvements"><span class="shortcut-icon">&#128221;</span>Review code</div>'`,
    `        + '</div></div>';`,
    `      break;`,

    `    case "threadList":`,
    `      var tl = document.getElementById("threadList"); tl.innerHTML = "";`,
    `      if (m.threads.length === 0) {`,
    `        tl.innerHTML = '<p style="text-align:center;color:var(--fg2);font-size:12px;padding:20px">No chat history yet</p>';`,
    `      } else {`,
    `        // Group threads by workspace`,
    `        var groups = {};`,
    `        var groupOrder = [];`,
    `        m.threads.forEach(function(t) {`,
    `          var key = t.workspacePath || "";`,
    `          if (!groups[key]) { groups[key] = []; groupOrder.push(key); }`,
    `          groups[key].push(t);`,
    `        });`,
    `        groupOrder.forEach(function(wsPath) {`,
    `          var wsThreads = groups[wsPath];`,
    `          var wsName = wsThreads[0].workspaceName || wsPath.split(/[\\/]/).pop() || "Unknown";`,
    `          var isCurrent = wsPath === m.currentWorkspacePath;`,
    `          // Project header`,
    `          var hdr = document.createElement("div");`,
    `          hdr.className = "thread-project-header" + (isCurrent ? " current-project" : "");`,
    `          hdr.innerHTML = '<span class="tph-icon">\uD83D\uDCC1</span><span class="tph-name">' + esc(wsName) + '</span>'`,
    `            + (isCurrent ? '<span class="tph-badge">current</span>' : '');`,
    `          tl.appendChild(hdr);`,
    `          wsThreads.forEach(function(t) {`,
    `            var ti3 = document.createElement("div");`,
    `            ti3.className = "thread-item" + (t.active ? " active" : "");`,
    `            ti3.innerHTML = '<span class="ti-icon">&#128172;</span>'`,
    `              + '<span class="ti-info">'`,
    `              + '<span class="ti-preview">' + esc(t.preview) + '</span>'`,
    `              + '<span class="ti-meta">' + esc(t.date) + ' &bull; ' + t.messageCount + ' messages</span>'`,
    `              + '</span>'`,
    `              + '<button class="ti-delete" data-delthread="' + t.id + '" title="Delete">&#128465;</button>';`,
    `            ti3.addEventListener("click", function(ev) {`,
    `              if (!ev.target.dataset.delthread) {`,
    `                vscodeApi.postMessage({type:"switchThread", id: t.id});`,
    `                document.getElementById("threadPanel").classList.remove("open");`,
    `              }`,
    `            });`,
    `            tl.appendChild(ti3);`,
    `          });`,
    `        });`,
    `      }`,
    `      break;`,
    `  }`,
    `});`,
  ].join("\n");
}
