/**
 * Returns the JavaScript code for the webview.
 */
export function getWebviewScript(): string {
  return [
    // ── Markdown renderer ──
    `function renderMd(src) {`,
    `  if (!src) return "";`,
    `  var h = "";`,
    `  var lines = src.split("\\n");`,
    `  var inCode = false, codeLang = "", codeLines = [];`,
    `  var inUl = false, inOl = false;`,
    `  for (var i = 0; i < lines.length; i++) {`,
    `    var line = lines[i];`,
    `    if (line.startsWith("\`\`\`")) {`,
    `      if (!inCode) {`,
    `        if (inUl) { h += "</ul>"; inUl = false; }`,
    `        if (inOl) { h += "</ol>"; inOl = false; }`,
    `        inCode = true; codeLang = line.slice(3).trim(); codeLines = [];`,
    `      } else {`,
    `        var cid = "c" + Math.random().toString(36).slice(2,8);`,
    `        h += '<pre><div class="code-head"><span>' + esc(codeLang||"text") + '</span><button class="copy-btn" data-codeid="' + cid + '">Copy</button></div><code id="' + cid + '">' + esc(codeLines.join("\\n")) + '</code></pre>';`,
    `        inCode = false; codeLang = ""; codeLines = [];`,
    `      }`,
    `      continue;`,
    `    }`,
    `    if (inCode) { codeLines.push(line); continue; }`,
    `    var isUlItem = /^[\\-\\*] /.test(line);`,
    `    var isOlItem = /^\\d+\\. /.test(line);`,
    `    if (inUl && !isUlItem) { h += "</ul>"; inUl = false; }`,
    `    if (inOl && !isOlItem) { h += "</ol>"; inOl = false; }`,
    `    if (line.indexOf("|") > -1 && i+1 < lines.length && /^[\\|\\s:\\-]+$/.test(lines[i+1])) {`,
    `      var headers = line.split("|").map(function(c){return c.trim();}).filter(Boolean);`,
    `      i++;`,
    `      h += '<table><thead><tr>';`,
    `      headers.forEach(function(hd){ h += '<th>' + inlineMd(esc(hd)) + '</th>'; });`,
    `      h += '</tr></thead><tbody>';`,
    `      while (i+1 < lines.length && lines[i+1].indexOf("|") > -1) {`,
    `        i++;`,
    `        var cells = lines[i].split("|").map(function(c){return c.trim();}).filter(Boolean);`,
    `        h += '<tr>';`,
    `        cells.forEach(function(cl){ h += '<td>' + inlineMd(esc(cl)) + '</td>'; });`,
    `        h += '</tr>';`,
    `      }`,
    `      h += '</tbody></table>'; continue;`,
    `    }`,
    `    if (line.startsWith("#### ")) { h += "<h4>" + inlineMd(esc(line.slice(5))) + "</h4>"; continue; }`,
    `    if (line.startsWith("### "))  { h += "<h3>" + inlineMd(esc(line.slice(4))) + "</h3>"; continue; }`,
    `    if (line.startsWith("## "))   { h += "<h2>" + inlineMd(esc(line.slice(3))) + "</h2>"; continue; }`,
    `    if (line.startsWith("# "))    { h += "<h1>" + inlineMd(esc(line.slice(2))) + "</h1>"; continue; }`,
    `    if (/^---+$/.test(line)) { h += "<hr/>"; continue; }`,
    `    if (line.startsWith("> ")) { h += "<blockquote>" + inlineMd(esc(line.slice(2))) + "</blockquote>"; continue; }`,
    `    if (isUlItem) {`,
    `      if (!inUl) { h += "<ul>"; inUl = true; }`,
    `      h += "<li>" + inlineMd(esc(line.replace(/^[\\-\\*] /,""))) + "</li>"; continue;`,
    `    }`,
    `    if (isOlItem) {`,
    `      if (!inOl) { h += "<ol>"; inOl = true; }`,
    `      h += "<li>" + inlineMd(esc(line.replace(/^\\d+\\. /,""))) + "</li>"; continue;`,
    `    }`,
    `    if (line.trim() === "") { h += "<br/>"; continue; }`,
    `    h += "<p>" + inlineMd(esc(line)) + "</p>";`,
    `  }`,
    `  if (inUl) h += "</ul>";`,
    `  if (inOl) h += "</ol>";`,
    `  if (inCode && codeLines.length > 0) {`,
    `    var cid2 = "c" + Math.random().toString(36).slice(2,8);`,
    `    h += '<pre><div class="code-head"><span>' + esc(codeLang||"text") + '</span></div><code id="' + cid2 + '">' + esc(codeLines.join("\\n")) + '</code></pre>';`,
    `  }`,
    `  return h;`,
    `}`,
    `function inlineMd(s) {`,
    `  s = s.replace(/\`([^\`]+)\`/g, '<code>$1</code>');`,
    `  s = s.replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>');`,
    `  s = s.replace(/__(.+?)__/g, '<strong>$1</strong>');`,
    `  s = s.replace(/\\*(.+?)\\*/g, '<em>$1</em>');`,
    `  s = s.replace(/_(.+?)_/g, '<em>$1</em>');`,
    `  s = s.replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '<a href="$2" target="_blank">$1</a>');`,
    `  return s;`,
    `}`,
    `function esc(t) { return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }`,

    // ── DOM refs ──
    `var vscodeApi = acquireVsCodeApi();`,
    `var chatEl = document.getElementById("chat");`,
    `var inputEl = document.getElementById("input");`,
    `var sendBtnEl = document.getElementById("sendBtn");`,
    `var generating = false, currentStreamEl = null, streamText = "";`,

    // ── Input auto-resize ──
    `inputEl.addEventListener("input", function() {`,
    `  inputEl.style.height = "24px";`,
    `  inputEl.style.height = Math.min(inputEl.scrollHeight, 120) + "px";`,
    `});`,
    `inputEl.addEventListener("keydown", function(e) {`,
    `  if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); doSend(); }`,
    `});`,
    `sendBtnEl.addEventListener("click", function() {`,
    `  if (generating) { vscodeApi.postMessage({type:"stopGeneration"}); }`,
    `  else { doSend(); }`,
    `});`,

    // ── Toolbar buttons ──
    `document.getElementById("pickFileBtn").addEventListener("click", function() { vscodeApi.postMessage({type:"pickFile"}); });`,
    `document.getElementById("newChatBtn").addEventListener("click", function() { vscodeApi.postMessage({type:"newChat"}); });`,
    `document.getElementById("threadsBtn").addEventListener("click", function() {`,
    `  vscodeApi.postMessage({type:"listThreads"});`,
    `  document.getElementById("threadPanel").classList.add("open");`,
    `  setTimeout(function() { document.getElementById("threadSearch").focus(); }, 100);`,
    `});`,
    `document.getElementById("closeThreads").addEventListener("click", function() {`,
    `  document.getElementById("threadPanel").classList.remove("open");`,
    `});`,

    // ── Thread search ──
    `var _allThreads = [];`,
    `function renderThreadList(threads) {`,
    `  var tl = document.getElementById("threadList"); tl.innerHTML = "";`,
    `  if (!threads || threads.length === 0) {`,
    `    tl.innerHTML = '<div class="tl-empty"><div class="tl-empty-icon">&#128172;</div><div>No chat history yet</div><div class="tl-empty-sub">Your conversations will appear here</div></div>';`,
    `    return;`,
    `  }`,
    `  var today = new Date(); today.setHours(0,0,0,0);`,
    `  var todayItems = [], olderItems = [];`,
    `  threads.forEach(function(t) {`,
    `    var d = new Date(t.rawDate || t.date); d.setHours(0,0,0,0);`,
    `    if (d >= today) todayItems.push(t); else olderItems.push(t);`,
    `  });`,
    `  function addGroup(label, items) {`,
    `    if (items.length === 0) return;`,
    `    var gl = document.createElement("div"); gl.className = "tg-label"; gl.textContent = label;`,
    `    tl.appendChild(gl);`,
    `    items.forEach(function(t) {`,
    `      var ti = document.createElement("div");`,
    `      ti.className = "thread-item" + (t.active ? " active" : "");`,
    `      var previewText = t.preview || "New chat";`,
    `      var dateStr = t.rawDate ? formatThreadDate(t.rawDate) : t.date;`,
    `      ti.innerHTML = '<div class="ti-main">'`,
    `        + '<div class="ti-preview">' + esc(previewText) + '</div>'`,
    `        + '<div class="ti-meta">' + esc(dateStr) + ' &middot; ' + t.messageCount + ' msg</div>'`,
    `        + '</div>'`,
    `        + '<div class="ti-actions">'`,
    `        + '<button class="ti-delete" data-delthread="' + esc(t.id) + '" title="Delete">&#128465;</button>'`,
    `        + '</div>';`,
    `      ti.addEventListener("click", function(ev) {`,
    `        if (ev.target.dataset && ev.target.dataset.delthread) {`,
    `          vscodeApi.postMessage({type:"deleteThread", id: ev.target.dataset.delthread});`,
    `        } else {`,
    `          vscodeApi.postMessage({type:"switchThread", id: t.id});`,
    `          document.getElementById("threadPanel").classList.remove("open");`,
    `        }`,
    `      });`,
    `      tl.appendChild(ti);`,
    `    });`,
    `  }`,
    `  addGroup("Today", todayItems);`,
    `  addGroup("Older", olderItems);`,
    `}`,
    `function formatThreadDate(isoStr) {`,
    `  var d = new Date(isoStr);`,
    `  var today = new Date(); today.setHours(0,0,0,0);`,
    `  var isToday = d >= today;`,
    `  var opts = isToday`,
    `    ? { hour: "numeric", minute: "2-digit", hour12: true }`,
    `    : { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", hour12: true };`,
    `  return d.toLocaleString("en-US", opts).replace(" at ", ", ");`,
    `}`,
    `document.getElementById("threadSearch").addEventListener("input", function() {`,
    `  var q = this.value.toLowerCase().trim();`,
    `  if (!q) { renderThreadList(_allThreads); return; }`,
    `  var filtered = _allThreads.filter(function(t) {`,
    `    return (t.preview || "").toLowerCase().includes(q);`,
    `  });`,
    `  renderThreadList(filtered);`,
    `});`,

    // ── Tool block helpers ──
    `function toolFilepath(fp) {`,
    `  if (!fp) return "";`,
    `  var p = fp.replace(/\\\\/g, "/");`,
    `  var parts = p.split("/"); var short = parts.length > 2 ? "\u2026/" + parts.slice(-2).join("/") : p;`,
    `  return '<span class="tool-fp" title="' + esc(fp) + '">' + esc(short) + '</span>';`,
    `}`,
    `function renderDiffBlock(oldStr, newStr) {`,
    `  var h = '<div class="diff-view">'; var MAX = 60; var shown = 0;`,
    `  (oldStr || "").split("\\n").forEach(function(l) { if (shown++ < MAX) h += '<div class="diff-line diff-del"><span class="diff-sym">-</span><span class="diff-code">' + esc(l) + '</span></div>'; });`,
    `  (newStr || "").split("\\n").forEach(function(l) { if (shown++ < MAX) h += '<div class="diff-line diff-add"><span class="diff-sym">+</span><span class="diff-code">' + esc(l) + '</span></div>'; });`,
    `  var total = (oldStr||"").split("\\n").length + (newStr||"").split("\\n").length;`,
    `  if (total > MAX) h += '<div class="diff-truncated">\u2026 ' + (total - MAX) + ' more lines not shown</div>';`,
    `  h += '</div>'; return h;`,
    `}`,
    `function renderNewFileBlock(content) {`,
    `  var lines = (content || "").split("\\n"); var MAX = 60;`,
    `  var h = '<div class="diff-view">';`,
    `  lines.slice(0, MAX).forEach(function(l) { h += '<div class="diff-line diff-add"><span class="diff-sym">+</span><span class="diff-code">' + esc(l) + '</span></div>'; });`,
    `  if (lines.length > MAX) h += '<div class="diff-truncated">\u2026 ' + (lines.length - MAX) + ' more lines</div>';`,
    `  h += '</div>'; return h;`,
    `}`,
    `function buildToolHtml(name, label, meta, input) {`,
    `  var n = (name || "").toLowerCase().replace(/tool$/, "");`,
    `  var spin = '<div class="tool-spinner"></div>';`,
    `  var chev = '<span class="tool-chevron">\u25BA</span>';`,
    `  var mid = ""; var body = ""; var autoOpen = false;`,
    `  if (n === "fileread" || n === "read_file") {`,
    `    var rfp = (input.file_path || input.path || "") + "";`,
    `    mid = '<span class="tool-icon">\uD83D\uDCC4</span><div class="tool-file-meta"><span class="tool-action-label">Reading</span>' + toolFilepath(rfp) + '</div>';`,
    `  } else if (n === "filewrite" || n === "write_file") {`,
    `    var wfp = (input.file_path || input.path || "") + ""; var wct = (input.content || "") + "";`,
    `    mid = '<span class="tool-icon">\uD83D\uDCDD</span><div class="tool-file-meta"><span class="tool-action-label">Writing</span>' + toolFilepath(wfp) + '</div>';`,
    `    if (wct) { body = renderNewFileBlock(wct); autoOpen = true; }`,
    `  } else if (n === "fileedit" || n === "edit_file") {`,
    `    var efp = (input.file_path || input.path || "") + "";`,
    `    var eos = (input.old_string || "") + ""; var ens = (input.new_string || "") + "";`,
    `    mid = '<span class="tool-icon">\u270F\uFE0F</span><div class="tool-file-meta"><span class="tool-action-label">Editing</span>' + toolFilepath(efp) + '</div>';`,
    `    if (eos || ens) { body = renderDiffBlock(eos, ens); autoOpen = true; }`,
    `  } else if (n === "bash") {`,
    `    var bcmd = (input.command || "") + "";`,
    `    mid = '<span class="tool-icon">\uD83D\uDCBB</span><span class="tool-label tool-cmd-preview">$ ' + esc(bcmd.split("\\n")[0].slice(0, 70)) + '</span>';`,
    `    body = '<div class="bash-cmd-wrap"><pre class="bash-cmd">' + esc(bcmd) + '</pre></div>'; autoOpen = true;`,
    `  } else if (n === "glob" || n === "grep") {`,
    `    var gPat = (input.pattern || "") + "";`,
    `    mid = '<span class="tool-icon">\uD83D\uDD0D</span><span class="tool-label">' + esc(label || name) + '</span>' + (gPat ? '<code class="tool-pattern">' + esc(gPat.slice(0, 50)) + '</code>' : '');`,
    `  } else if (n === "listdirectory") {`,
    `    var ldp = (input.path || "") + "";`,
    `    mid = '<span class="tool-icon">\uD83D\uDCC1</span><div class="tool-file-meta"><span class="tool-action-label">Listing</span>' + toolFilepath(ldp) + '</div>';`,
    `  } else if (n === "webfetch") {`,
    `    var wfu = (input.url || "") + "";`,
    `    mid = '<span class="tool-icon">\uD83C\uDF10</span><span class="tool-label">' + esc(label || "Fetching") + '</span>' + (wfu ? '<code class="tool-pattern">' + esc(wfu.replace(/^https?:\\/\\//, "").slice(0, 50)) + '</code>' : '');`,
    `  } else if (n === "todowrite") {`,
    `    mid = '<span class="tool-icon">\uD83D\uDCCB</span><span class="tool-label">Updating tasks</span>';`,
    `  } else {`,
    `    var gStr = typeof input === "object" ? Object.keys(input).slice(0,3).map(function(k){return k+": "+String(input[k]).slice(0,30);}).join(" \u00b7 ") : "";`,
    `    mid = '<span class="tool-icon">' + meta.icon + '</span><span class="tool-label">' + esc(label || name) + '</span>';`,
    `    if (gStr) { body = '<pre class="tool-generic-input">' + esc(gStr) + '</pre>'; }`,
    `  }`,
    `  var openAttr = autoOpen ? ' data-open="1"' : '';`,
    `  return '<div class="tool-head"' + openAttr + '>' + chev + mid + spin + '</div><div class="tool-body">' + body + '</div>';`,
    `}`,

    // ── Tool metadata (icon + color category) ──
    `var TOOL_META = {`,
    `  bash:         { icon: "\uD83D\uDCBB", cat: "exec" },`,
    `  fileread:     { icon: "\uD83D\uDCC4", cat: "read" },`,
    `  read_file:    { icon: "\uD83D\uDCC4", cat: "read" },`,
    `  filewrite:    { icon: "\u270F\uFE0F",  cat: "write" },`,
    `  write_file:   { icon: "\u270F\uFE0F",  cat: "write" },`,
    `  fileedit:     { icon: "\u270F\uFE0F",  cat: "write" },`,
    `  edit_file:    { icon: "\u270F\uFE0F",  cat: "write" },`,
    `  glob:         { icon: "\uD83D\uDD0D", cat: "read" },`,
    `  grep:         { icon: "\uD83D\uDD0D", cat: "read" },`,
    `  listdirectory:{ icon: "\uD83D\uDCC1", cat: "read" },`,
    `  ls:           { icon: "\uD83D\uDCC1", cat: "read" },`,
    `  webfetch:     { icon: "\uD83C\uDF10", cat: "net" },`,
    `  todowrite:    { icon: "\uD83D\uDCCB", cat: "info" },`,
    `};`,
    `function toolMeta(name) {`,
    `  var key = (name||"").toLowerCase().replace(/tool$/,"");`,
    `  return TOOL_META[key] || { icon: "\uD83D\uDD27", cat: "info" };`,
    `}`,

    // ── Delegated click handler ──
    `document.addEventListener("click", function(e) {`,
    `  var el = e.target;`,
    `  if (el.dataset && el.dataset.prompt) { inputEl.value = el.dataset.prompt; doSend(); }`,
    `  if (el.classList.contains("copy-btn") && el.dataset.codeid) {`,
    `    var codeEl = document.getElementById(el.dataset.codeid);`,
    `    if (codeEl) { navigator.clipboard.writeText(codeEl.textContent||""); el.textContent="Copied!"; setTimeout(function(){el.textContent="Copy";},1800); }`,
    `  }`,
    `  var toolHead = el.classList.contains("tool-head") ? el : (el.closest ? el.closest(".tool-head") : null);`,
    `  if (toolHead) { toolHead.closest(".tool").classList.toggle("open"); }`,
    `  var thinkHead = el.classList.contains("thinking-head") ? el : (el.closest ? el.closest(".thinking-head") : null);`,
    `  if (thinkHead) { thinkHead.closest(".thinking-block").classList.toggle("open"); }`,
    `  if (el.dataset && el.dataset.delthread) {`,
    `    e.stopPropagation();`,
    `    vscodeApi.postMessage({type:"deleteThread", id: el.dataset.delthread});`,
    `  }`,
    `});`,

    // ── Send ──
    `function doSend() {`,
    `  var t = inputEl.value.trim();`,
    `  if (!t || generating) return;`,
    `  vscodeApi.postMessage({ type: "sendMessage", text: t });`,
    `  inputEl.value = ""; inputEl.style.height = "24px";`,
    `}`,

    // ── Add message bubble ──
    `function addMsg(role, content) {`,
    `  var w = chatEl.querySelector(".welcome"); if(w) w.remove();`,
    `  var d = document.createElement("div"); d.className = "msg " + role;`,
    `  var avatarLetter = role === "user" ? "U" : "M";`,
    `  var displayName  = role === "user" ? "You" : "Milo Code";`,
    `  var body = role === "assistant" ? renderMd(content) : "<p>" + esc(content) + "</p>";`,
    `  d.innerHTML = '<div class="msg-head"><div class="avatar">' + avatarLetter + '</div><span class="msg-name">' + displayName + '</span></div><div class="msg-body">' + body + '</div>';`,
    `  chatEl.appendChild(d); chatEl.scrollTop = chatEl.scrollHeight; return d;`,
    `}`,

    // ── Processing indicator helper ──
    `function showProcessing() {`,
    `  removeProcessing();`,
    `  var ti = document.createElement("div");`,
    `  ti.id = "thinking-indicator"; ti.className = "msg assistant";`,
    `  ti.innerHTML = '<div class="msg-head"><div class="avatar">M</div><span class="msg-name">Milo Code</span></div>'`,
    `    + '<div class="msg-body thinking-wrap">'`,
    `    + '<span class="thinking-dots"><span></span><span></span><span></span></span>'`,
    `    + '<span class="thinking-label">Processing...</span>'`,
    `    + '</div>';`,
    `  chatEl.appendChild(ti); chatEl.scrollTop = chatEl.scrollHeight;`,
    `}`,
    `function removeProcessing() {`,
    `  var ti = document.getElementById("thinking-indicator"); if(ti) ti.remove();`,
    `}`,

    // ── Message handler ──
    `window.addEventListener("message", function(e) {`,
    `  var m = e.data;`,
    `  switch(m.type) {`,

    `    case "addMessage": addMsg(m.role, m.content); break;`,

    `    case "generationStarted":`,
    `      generating = true;`,
    `      sendBtnEl.innerHTML = "&#9632; Stop";`,
    `      sendBtnEl.className = "stop";`,
    `      var w2 = chatEl.querySelector(".welcome"); if(w2) w2.remove();`,
    `      showProcessing();`,
    `      break;`,

    `    case "streamStart":`,
    `      streamText = "";`,
    `      removeProcessing();`,
    `      currentStreamEl = addMsg("assistant", "");`,
    `      break;`,

    `    case "streamDelta":`,
    `      streamText += m.text || "";`,
    `      if (currentStreamEl) currentStreamEl.querySelector(".msg-body").innerHTML = renderMd(streamText);`,
    `      chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,

    `    case "streamEnd": currentStreamEl = null; streamText = ""; break;`,

    `    case "generationStopped":`,
    `      generating = false;`,
    `      sendBtnEl.innerHTML = "&#10148; Send";`,
    `      sendBtnEl.className = "";`,
    `      removeProcessing();`,
    `      break;`,

    `    case "toolBlock": {`,
    `      removeProcessing();`,
    `      var tMeta = toolMeta(m.name);`,
    `      var tInp = {};`,
    `      try { tInp = JSON.parse(m.input || "null") || {}; } catch(ex) {}`,
    `      var tb = document.createElement("div");`,
    `      tb.className = "tool tool-cat-" + tMeta.cat; tb.id = "tool-" + m.id;`,
    `      tb.setAttribute("data-toolname", m.name || "");`,
    `      tb.innerHTML = buildToolHtml(m.name, m.label, tMeta, tInp);`,
    `      if (tb.querySelector("[data-open]")) tb.classList.add("open");`,
    `      chatEl.appendChild(tb); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,
    `    }`,

    `    case "toolBlockUpdate": {`,
    `      var existing = document.getElementById("tool-" + m.id);`,
    `      if (existing) {`,
    `        var spinner = existing.querySelector(".tool-spinner");`,
    `        if (spinner) {`,
    `          var badge = document.createElement("span");`,
    `          if (m.status === "error") { badge.className = "tool-badge err"; badge.textContent = "\u2717 Error"; }`,
    `          else { badge.className = "tool-badge ok"; badge.textContent = "\u2713 Done"; }`,
    `          spinner.replaceWith(badge);`,
    `        }`,
    `        if (m.output) {`,
    `          var tnn = (existing.getAttribute("data-toolname") || "").toLowerCase().replace(/tool$/, "");`,
    `          var bd = existing.querySelector(".tool-body");`,
    `          var isFileTool = tnn === "filewrite" || tnn === "fileedit" || tnn === "fileread" || tnn === "write_file" || tnn === "edit_file" || tnn === "read_file" || tnn === "create" || tnn === "todowrite" || tnn === "todo_write";`,
    `          if (bd && (!isFileTool || m.status === "error")) {`,
    `            var outSec = document.createElement("div");`,
    `            outSec.className = "tool-section " + (m.status === "error" ? "tool-output-err" : "tool-output-ok");`,
    `            if (tnn === "bash") {`,
    `              var oLines = m.output.split("\\n"); var oId = "bo-" + m.id;`,
    `              var oClamp = oLines.length > 30 ? " bash-output-clamp" : "";`,
    `              outSec.innerHTML = '<div class="tool-section-head">Output (' + oLines.length + ' lines)</div>'`,
    `                + '<pre id="' + oId + '" class="bash-output' + oClamp + '">' + esc(m.output) + '</pre>';`,
    `              if (oClamp) outSec.innerHTML += '<button class="show-more-btn" onclick="document.getElementById(\\'' + oId + '\\').classList.remove(\\'bash-output-clamp\\');this.remove()">Show ' + (oLines.length - 30) + ' more lines</button>';`,
    `            } else {`,
    `              outSec.innerHTML = '<div class="tool-section-head">Output</div><pre>' + esc(m.output.slice(0, 500)) + (m.output.length > 500 ? "\u2026" : "") + '</pre>';`,
    `            }`,
    `            bd.appendChild(outSec);`,
    `          }`,
    `          if (tnn === "bash" || tnn === "webfetch" || tnn === "grep" || tnn === "glob" || tnn === "listdirectory" || m.status === "error") {`,
    `            existing.classList.add("open");`,
    `          }`,
    `        }`,
    `      }`,
    `      break;`,
    `    }`,

    `    case "thinkingStart": {`,
    `      removeProcessing();`,
    `      var tk = document.createElement("div");`,
    `      tk.className = "thinking-block"; tk.id = m.id;`,
    `      tk.innerHTML = '<div class="thinking-head">'`,
    `        + '<span class="thinking-chevron">\u25BA</span>'`,
    `        + '<span class="thinking-head-label">\uD83E\uDDE0 Thinking...</span>'`,
    `        + '<div class="thinking-stream-dots"><span></span><span></span><span></span></div>'`,
    `        + '</div>'`,
    `        + '<div class="thinking-body"></div>';`,
    `      chatEl.appendChild(tk); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,
    `    }`,

    `    case "thinkingDelta": {`,
    `      var tkEl = document.getElementById(m.id);`,
    `      if (tkEl) {`,
    `        var tbody = tkEl.querySelector(".thinking-body");`,
    `        if (tbody) {`,
    `          tbody.innerHTML += "<p>" + esc(m.text || "") + "</p>";`,
    `          chatEl.scrollTop = chatEl.scrollHeight;`,
    `        }`,
    `      }`,
    `      break;`,
    `    }`,

    `    case "thinkingEnd": {`,
    `      var tkEl2 = document.getElementById(m.id);`,
    `      if (tkEl2) {`,
    `        var dots = tkEl2.querySelector(".thinking-stream-dots");`,
    `        if (dots) {`,
    `          var bodyText = (tkEl2.querySelector(".thinking-body")||{textContent:""}).textContent||"";`,
    `          var cc = document.createElement("span");`,
    `          cc.className = "thinking-char-count"; cc.textContent = bodyText.trim().length + " chars";`,
    `          dots.replaceWith(cc);`,
    `        }`,
    `        var lbl = tkEl2.querySelector(".thinking-head-label");`,
    `        if (lbl) lbl.textContent = "\uD83E\uDDE0 Thought";`,
    `      }`,
    `      break;`,
    `    }`,

    `    case "todoUpdate":`,
    `      var todoEl = document.getElementById("todo-panel");`,
    `      if (!todoEl) {`,
    `        todoEl = document.createElement("div");`,
    `        todoEl.id = "todo-panel";`,
    `        todoEl.className = "todo-panel";`,
    `        var chatParent = chatEl.parentNode;`,
    `        chatParent.insertBefore(todoEl, chatEl);`,
    `      }`,
    `      todoEl.innerHTML = '<div class="todo-header">&#128203; Task progress</div>'`,
    `        + m.todos.map(function(t) {`,
    `          var icon = t.status === "done" ? "&#10003;" : t.status === "in_progress" ? "&#9654;" : t.status === "blocked" ? "&#10007;" : "&#9675;";`,
    `          var cls = "todo-item todo-" + t.status;`,
    `          return '<div class="' + cls + '">' + icon + ' <span class="todo-title">' + esc(t.title) + '</span>'`,
    `            + (t.note ? '<span class="todo-note">' + esc(t.note) + '</span>' : '') + '</div>';`,
    `        }).join("");`,
    `      break;`,

    `    case "permissionPrompt": {`,
    `      removeProcessing();`,
    `      var toolM = toolMeta(m.name);`,
    `      var isExec = m.name === "bash" || m.name === "Bash";`,
    `      var actionLabel = isExec ? "run a shell command" : "perform an action";`,
    `      var pp = document.createElement("div"); pp.className = "permission-prompt";`,
    `      pp.innerHTML = '<div class="pp-header">'`,
    `          + '<span class="pp-icon">' + toolM.icon + '</span>'`,
    `          + '<div class="pp-header-text">'`,
    `          + '<div class="pp-title">Milo Code wants to ' + actionLabel + '</div>'`,
    `          + '<div class="pp-subtitle">' + esc(m.name) + '</div>'`,
    `          + '</div>'`,
    `          + '</div>'`,
    `        + '<pre class="pp-input">' + esc((m.input||"").slice(0,600)) + ((m.input||"").length>600?"\u2026":"") + '</pre>'`,
    `        + '<div class="pp-actions">'`,
    `        + '<button class="pp-btn pp-deny" data-perm="deny">\u2715 Deny</button>'`,
    `        + '<button class="pp-btn pp-allow" data-perm="allow">\u2713 Allow once</button>'`,
    `        + '<button class="pp-btn pp-allowall" data-perm="allow_all">\u26A1 Allow all for this session</button>'`,
    `        + '</div>';`,
    `      pp.querySelectorAll(".pp-btn").forEach(function(btn) {`,
    `        btn.addEventListener("click", function() {`,
    `          vscodeApi.postMessage({type:"permissionResponse", answer: btn.dataset.perm});`,
    `          pp.remove();`,
    `        });`,
    `      });`,
    `      chatEl.appendChild(pp); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,
    `    }`,

    `    case "showError":`,
    `      removeProcessing();`,
    `      var errD = document.createElement("div"); errD.className = "tool";`,
    `      errD.innerHTML = '<div class="tool-head"><span class="tool-name">&#10060; Error</span><span class="tool-status err">failed</span></div>'`,
    `        + '<div class="tool-body open"><pre>' + esc(m.error) + '</pre></div>';`,
    `      chatEl.appendChild(errD); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      break;`,

    `    case "downloadProgress":`,
    `      var dlEl = document.getElementById("milo-download-progress");`,
    `      if (!dlEl) {`,
    `        dlEl = document.createElement("div"); dlEl.id = "milo-download-progress";`,
    `        dlEl.style.cssText = "padding:8px 12px;font-size:12px;color:var(--fg2);display:flex;align-items:center;gap:8px";`,
    `        dlEl.innerHTML = '<span>&#11015;&#65039;</span><span id="milo-dl-text"></span><div style="flex:1;height:3px;background:var(--bg2);border-radius:2px;overflow:hidden"><div id="milo-dl-bar" style="height:100%;background:var(--accent);transition:width 0.2s;width:0%"></div></div>';`,
    `        chatEl.appendChild(dlEl); chatEl.scrollTop = chatEl.scrollHeight;`,
    `      }`,
    `      document.getElementById("milo-dl-text").textContent = m.text;`,
    `      document.getElementById("milo-dl-bar").style.width = m.progress + "%";`,
    `      if (m.progress >= 100) { setTimeout(function(){ var e=document.getElementById("milo-download-progress"); if(e) e.remove(); }, 2000); }`,
    `      break;`,

    `    case "clearChat":`,
    `      chatEl.innerHTML = '<div class="welcome">'`,
    `        + '<div class="welcome-logo">&#129302;</div>'`,
    `        + '<h2>Milo Code</h2>'`,
    `        + '<span class="tag">Powered by Gemma 4 &nbsp;&#183;&nbsp; Self-hosted</span>'`,
    `        + '<p>AI coding agent inside VS Code.<br>Read, write, edit files &bull; run commands &bull; persistent chat history.</p>'`,
    `        + '<div class="shortcuts">'`,
    `        + '<div class="shortcut" data-prompt="Explain this project structure to me"><span class="shortcut-icon">&#128269;</span>Explain project</div>'`,
    `        + '<div class="shortcut" data-prompt="Find and fix bugs in the code"><span class="shortcut-icon">&#128030;</span>Find &amp; fix bugs</div>'`,
    `        + '<div class="shortcut" data-prompt="Write unit tests for this project"><span class="shortcut-icon">&#9989;</span>Write tests</div>'`,
    `        + '<div class="shortcut" data-prompt="Review the code and suggest improvements"><span class="shortcut-icon">&#128221;</span>Review code</div>'`,
    `        + '</div></div>';`,
    `      break;`,

    `    case "threadList":`,
    `      var pnEl = document.getElementById("tp-project-name");`,
    `      if (pnEl && m.projectName) pnEl.textContent = m.projectName;`,
    `      _allThreads = (m.threads || []).map(function(t) {`,
    `        return { id: t.id, preview: t.preview || "New chat", date: t.date, rawDate: t.updatedAt || t.date, messageCount: t.messageCount, active: t.active };`,
    `      });`,
    `      var searchEl = document.getElementById("threadSearch");`,
    `      var q = searchEl ? searchEl.value.toLowerCase().trim() : "";`,
    `      var displayed = q ? _allThreads.filter(function(t) { return (t.preview||"").toLowerCase().includes(q); }) : _allThreads;`,
    `      renderThreadList(displayed);`,
    `      break;`,
    `  }`,
    `});`,
  ].join("\n");
}
